global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: app-v2-api
    scrape_interval: 30s
    scrape_timeout: 20s
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:9469
        labels:
          app: app-v2
          environment: production-v2
